/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CreateUserBody {
  email: string;
  username: string;
  displayname: string;
  photoUrl: string;
  isVerified?: boolean;
  [k: string]: unknown;
}
