/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CatSearchBody {
  city: string;
  country: string;
  gender?: string;
  age?: string;
  breed?: string;
  vaccinated?: string;
  spayedOrNeutered?: string;
  offset?: number;
  [k: string]: unknown;
}
